//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReMoBi_DCSN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiviet
    {
        public int id { get; set; }
        public string tenbaiviet { get; set; }
        public string tentacgia { get; set; }
        public string usernametacgia { get; set; }
        public System.DateTime ngaydang { get; set; }
        public Nullable<int> luotthich { get; set; }
        public string linkbaiviet { get; set; }
        public string linkfolderhinhanh { get; set; }
    
        public virtual dangnhap dangnhap { get; set; }
    }
}
